### ISSUE TITLE
Multiple lookup paths

### ISSUE THREAD

**Issue by milesj** [mrjoelkemp/node-dependency-tree#23]
First off, thank you so much for this library. I've tried a handful of dependency tree libraries that simply didn't work, or didn't do what I needed. This is the first one that's done almost everything I need, and is blazingly fast at it.

I was wondering if the library currently supports (didn't see anything in the source) the ability to define multiple lookup paths, besides the JS source root. For example, I include lodash functionality into my modules: https://github.com/titon/toolkit/blob/3.0/js-es6/Element.js#L9 Currently the library will skip over the lodash modules.

Perhaps something like a SystemJS style path map: https://github.com/titon/toolkit/blob/3.0/tests-es6/runner.js#L16

**Comment by mrjoelkemp** [comment]
Hey @milesj. Thanks for the kind words. Glad the lib is helpful.

The partial resolution algorithm that's currently in place is really naive. I just made an issue to swap it out with a (not totally complete) partial resolution factory ([filing-cabinet](https://github.com/mrjoelkemp/node-filing-cabinet)) that complements [precinct](https://github.com/mrjoelkemp/node-precinct).

Once that's in, we'll be able to properly resolve imports like `require('lodash')` and then (hopefully) continue recursing through lodash's tree to paint a complete picture – without the need for additional paths.

There will be an optimization necessary to avoid double parsing files (once for precinct to extract the dependencies and another parse for filing-cabinet to know which resolver to use). One way around that is to have consumers supply the resolver module if they don't want to support multiple JS module syntaxes.

This lib needs to support various configurations (requirejs, webpack, and systemjs) to be really robust against aliased paths. I can land requirejs support relatively quickly and have webpack planned for use in [Dependents](https://packagecontrol.io/packages/Dependents). SystemJS support isn't planned.

A bit of a brain dump so that I have an idea of what needs to happen to resolve your issue in the ideal case.

At the very minimum, I need to fix https://github.com/mrjoelkemp/node-filing-cabinet/issues/2 to get CommonJs resolution working and then bring filing-cabinet in. Will try to get them in soon, but I can't promise by a certain date.

**Comment by milesj** [comment]
This is all sounds great! No need to rush however as I'm currently tinkering around with some build tools in my free time, but will definitely keep my eye on this.

**Comment by SimenB** [comment]
Any news here? :smile:

**Comment by mrjoelkemp** [comment]
:) out of the country for another week. The changes to filing cabinet landed for proper commonjs support. Using filing cabinet in this lib is now possible. Open to a PR that does the integration; otherwise, I'll get to it the following week.

**Comment by milesj** [comment]
Glad to here it's making progress!

**Comment by mrjoelkemp** [comment]
@milesj @SimenB Ok, so I landed the filing-cabinet integration and cut a major release (v4.0.0). 

I chose to make a breaking change to the api to make it easier to support future configuration options. As stated earlier, webpack support will be in the pipeline – which would require a new configuration option. The new options didn't play well with the non-object form. Please see [the readme](https://github.com/mrjoelkemp/node-dependency-tree#usage) for the new form. If you're using this on an AMD app, you can supply the location to your requirejs config by passing in the new `config` property as part of the object. *Note: This may be buggy since https://github.com/mrjoelkemp/node-module-lookup-amd has some rough edges.*

Let me know if you have any questions and if the recent release addresses your concerns in this issue. Happy to reopen if including 3rd party modules in the tree isn't enough.

**Comment by SimenB** [comment]
Sounds good!

My use case is 3rd party modules in a webpack project, so half-way there. is there an issue I can track for webpack?

**Comment by mrjoelkemp** [comment]
Feel free to make one. I'd appreciate it.

Thanks!

**Comment by SimenB** [comment]
@mrjoelkemp #27

**Comment by mrjoelkemp** [comment]
Cheers!

**Comment by milesj** [comment]
Thanks for all the hard work, but it looks like I can't use it since I'm using ES7 syntax, heh.

**Comment by mrjoelkemp** [comment]
I should probably just switch to babel's parser since acorn's loose parser
isn't working for you.

Have a public repo that I can test on?

Thanks!

**Comment by milesj** [comment]
Perhaps allow the parser to be customized? Would allow for more complex implementations, like mine.

Here's the task in question. It may not be 100% correct right now as I was trying a bunch of things. https://github.com/titon/toolkit/blob/3.0/tasks/build-js.js#L42

**Comment by mrjoelkemp** [comment]
Thanks for the link.

> Perhaps allow the parser to be customized? Would allow for more complex
implementations, like mine.

The only benefit that I can see would be to share a parser across tools.
That's just avoiding another dependency for no foreseeable gain.
Realistically, I only need a few AST nodes that revolve around importing
and exporting modules (across module syntaxes). Babel's parser covers all
of those cases and doesn't choke on newer syntax.

I think swapping out the underlying parser could work. It's a change that
would have to happen in node-source-walk. Will likely make that change as
it makes all these tools future-proof.

Thanks!

**Comment by milesj** [comment]
That would be awesome. Thanks for all your hard work! Very much appreciated.

Just a note on the Babel stuff. It would most likely be necessary to pass custom Babel config options, for enabling ES7 features and such.

**Comment by mrjoelkemp** [comment]
Good point on the config options. I really just want a parser that doesn't shit itself. Acorn has the loose parser which precinct is using, but it needs to be integrated all the way down. Alternatively, yeah, the babel parser with the most lenient config would be good for avoiding parse errors.
