### ISSUE TITLE
Problem with resolving absolute paths in AMD modules

### ISSUE THREAD

**Issue by pahen** [mrjoelkemp/node-dependency-tree#40]
When running `dependency-tree --directory test/files/amd/ok test/files/amd/ok/a.js` on the file https://github.com/pahen/madge/blob/develop/test/files/amd/ok/a.js I get this:

```
{
  "/Users/patrik/Code/madge/test/files/amd/ok/a.js": {
    "/Users/patrik/Code/madge/test/files/amd/ok/sub/b.js": {}
  }
}
```

When I expected this:

```
{
  "/Users/patrik/Code/madge/test/files/amd/ok/a.js": {
    "/Users/patrik/Code/madge/test/files/amd/ok/sub/b.js": {
      "/Users/patrik/Code/madge/test/files/amd/ok/sub/c.js": {
        "/Users/patrik/Code/madge/test/files/amd/ok/d.js": {}
      }
    }
  }
}
```

If I create a RequireJS config with `baseUrl: '.'` and run `dependency-tree --directory test/files/amd/ok --require-config test/files/amd/ok/config.js test/files/amd/ok/a.js` I get this:

```
{
  "/Users/patrik/Code/madge/test/files/amd/ok/a.js": {
    "test/files/amd/ok/sub/b.js": {
      "test/files/amd/ok/sub/c.js": {
        "test/files/amd/ok/d.js": {}
      }
    }
  }
}
```

Which is almost what I expected except the wrong paths. Do you have any thoughts on this @mrjoelkemp?

**Comment by mrjoelkemp** [comment]
Thanks for reporting @pahen! The logic for amd partial resolution happens here: https://github.com/mrjoelkemp/node-module-lookup-amd/blob/master/index.js. 

The problem is that without a requirejs config specified, we assume that the [`baseUrl` is a dot](https://github.com/mrjoelkemp/node-module-lookup-amd/blob/master/index.js#L40) and we assume that the config could have been located in the directory of the `filename` (https://github.com/mrjoelkemp/node-module-lookup-amd/blob/master/index.js#L23). That's fine for a.js, since that's in the same location where the unspecified requirejs config would have been; but this doesn't hold for nested files like b.js. The solution, if a user doesn't want to supply a config, is to set the [`configPath` setting](https://github.com/mrjoelkemp/node-module-lookup-amd/blob/master/index.js#L23) to the location of where that config should have been. Any suggestions are welcome on improving this. Perhaps making the config required is the only sane path forward.

So the second attempt with a real config works well in handling nested dependencies since it's [correctly setting `configPath`](https://github.com/mrjoelkemp/node-module-lookup-amd/blob/9baec9eb3f9d2da556fb2837760637462b05dac5/index.js#L32-L36). The incorrect absolute paths could be the fault of https://github.com/mrjoelkemp/node-module-lookup-amd/blob/9baec9eb3f9d2da556fb2837760637462b05dac5/index.js#L60. If you use `DEBUG=*`, and paste the output of the call with the requirejs config specified, I'll know for sure.

Let me know your thoughts.

**Comment by pahen** [comment]
Here's the output from `DEBUG=* dependency-tree --directory test/files/amd/ok --require-config test/files/amd/ok/config.js test/files/amd/ok/a.js`

```
  tree given filename: test/files/amd/ok/a.js +0ms
  tree resolved filename: /Users/patrik/Code/madge/test/files/amd/ok/a.js +3ms
  tree visited:  +2ms {}
  tree traversing /Users/patrik/Code/madge/test/files/amd/ok/a.js +14ms
  tree extracted 1 dependencies:  +27ms [ 'sub/b' ]
  cabinet found a resolver for .js +2ms
  cabinet using amd resolver +0ms
  lookup config:  +1ms test/files/amd/ok/config.js
  lookup partial:  +0ms sub/b
  lookup filename:  +0ms /Users/patrik/Code/madge/test/files/amd/ok/a.js
  lookup converting given config file test/files/amd/ok/config.js to an object:
 +8ms { baseUrl: '.' }
  lookup configPath:  +0ms test/files/amd/ok/config.js
  lookup module resolution directory: test/files/amd/ok +1ms
  lookup normalized module id: ./sub/b +1ms
  lookup resolved url: test/files/amd/ok/sub/b +0ms
  lookup looking for file like test\/files\/amd\/ok\/sub\/b\. +1ms
  lookup within test/files/amd/ok/sub +0ms
  lookup found the following matches:  +2ms test/files/amd/ok/sub/b.js
  lookup found file like test/files/amd/ok/sub/b: test/files/amd/ok/sub/b.js +0ms
  cabinet resolved path for sub/b: test/files/amd/ok/sub/b.js +0ms
  tree cabinet result test/files/amd/ok/sub/b.js +0ms
  tree given filename: /Users/patrik/Code/madge/test/files/amd/ok/a.js +1ms
  tree resolved filename: /Users/patrik/Code/madge/test/files/amd/ok/a.js +0ms
  tree visited:  +0ms { '/Users/patrik/Code/madge/test/files/amd/ok/a.js': {} }
  tree traversing test/files/amd/ok/sub/b.js +1ms
  tree extracted 1 dependencies:  +8ms [ 'sub/c' ]
  cabinet found a resolver for .js +0ms
  cabinet using amd resolver +0ms
  lookup config:  +0ms test/files/amd/ok/config.js
  lookup partial:  +0ms sub/c
  lookup filename:  +0ms test/files/amd/ok/sub/b.js
  lookup converting given config file test/files/amd/ok/config.js to an object:
 +2ms { baseUrl: '.' }
  lookup configPath:  +0ms test/files/amd/ok/config.js
  lookup module resolution directory: test/files/amd/ok +0ms
  lookup normalized module id: ./sub/c +0ms
  lookup resolved url: test/files/amd/ok/sub/c +0ms
  lookup looking for file like test\/files\/amd\/ok\/sub\/c\. +0ms
  lookup within test/files/amd/ok/sub +0ms
  lookup found the following matches:  +1ms test/files/amd/ok/sub/c.js
  lookup found file like test/files/amd/ok/sub/c: test/files/amd/ok/sub/c.js +0ms
  cabinet resolved path for sub/c: test/files/amd/ok/sub/c.js +0ms
  tree cabinet result test/files/amd/ok/sub/c.js +0ms
  tree given filename: test/files/amd/ok/sub/b.js +0ms
  tree resolved filename: /Users/patrik/Code/madge/test/files/amd/ok/sub/b.js +0ms
  tree visited:  +0ms { '/Users/patrik/Code/madge/test/files/amd/ok/a.js': {},
  'test/files/amd/ok/sub/b.js': {} }
  tree traversing test/files/amd/ok/sub/c.js +0ms
  tree extracted 1 dependencies:  +3ms [ 'd' ]
  cabinet found a resolver for .js +0ms
  cabinet using amd resolver +8ms
  lookup config:  +0ms test/files/amd/ok/config.js
  lookup partial:  +0ms d
  lookup filename:  +0ms test/files/amd/ok/sub/c.js
  lookup converting given config file test/files/amd/ok/config.js to an object:
 +1ms { baseUrl: '.' }
  lookup configPath:  +1ms test/files/amd/ok/config.js
  lookup module resolution directory: test/files/amd/ok +0ms
  lookup normalized module id: ./d +0ms
  lookup resolved url: test/files/amd/ok/d +0ms
  lookup looking for file like test\/files\/amd\/ok\/d\. +0ms
  lookup within test/files/amd/ok +0ms
  lookup found the following matches:  +0ms test/files/amd/ok/d.js
  lookup found file like test/files/amd/ok/d: test/files/amd/ok/d.js +0ms
  cabinet resolved path for d: test/files/amd/ok/d.js +0ms
  tree cabinet result test/files/amd/ok/d.js +0ms
  tree given filename: test/files/amd/ok/sub/c.js +0ms
  tree resolved filename: /Users/patrik/Code/madge/test/files/amd/ok/sub/c.js +0ms
  tree visited:  +0ms { '/Users/patrik/Code/madge/test/files/amd/ok/a.js': {},
  'test/files/amd/ok/sub/b.js': {},
  'test/files/amd/ok/sub/c.js': {} }
  tree traversing test/files/amd/ok/d.js +1ms
  tree extracted 0 dependencies:  +0ms []
  tree traversal complete +0ms { 'test/files/amd/ok/sub/b.js': { 'test/files/amd/ok/sub/c.js': { 'test/files/amd/ok/d.js': {} } } }
  tree object form of results requested +1ms
  tree final tree +0ms { '/Users/patrik/Code/madge/test/files/amd/ok/a.js': { 'test/files/amd/ok/sub/b.js': { 'test/files/amd/ok/sub/c.js': [Object] } } }

{"/Users/patrik/Code/madge/test/files/amd/ok/a.js":{"test/files/amd/ok/sub/b.js":{"test/files/amd/ok/sub/c.js":{"test/files/amd/ok/d.js":{}}}}}
```

I think it would be very nice if this could work without a config. I suppose this would be fixed if we had a way to set `configPath` to the directory specified with the `--directory` parameter then?

**Comment by mrjoelkemp** [comment]
Thanks for the output! The paths not being absolute seems to be the result of the `config` not being absolute. That's a bug that should likely be handled with a `path.resolve(configPath)` [here](https://github.com/mrjoelkemp/node-module-lookup-amd/blob/9baec9eb3f9d2da556fb2837760637462b05dac5/index.js#L33). The fix should also have a test ensuring that the resulting subtree has an absolute path even with a relative `config` (and subsequent `configPath`) value. Would you be up for submitting the PR? It would get pushed through as a patch release, which would pass through to filing-cabinet (based on its [semver rule for module-lookup-amd](https://github.com/mrjoelkemp/node-filing-cabinet/blob/master/package.json#L50)).

> I think it would be very nice if this could work without a config. I suppose this would be fixed if we had a way to set configPath to the directory specified with the --directory parameter then?

Yes. I had support for a `directory` option in a previous version but it wasn't used when I switched over to using requirejs proper for resolution. We could modify the [defaulting of the configPath](https://github.com/mrjoelkemp/node-module-lookup-amd/blob/9baec9eb3f9d2da556fb2837760637462b05dac5/index.js#L23) to be `options.configPath || options.directory || options.filename`. The use of `directory` in that position would be problematic for [this line though](https://github.com/mrjoelkemp/node-module-lookup-amd/blob/9baec9eb3f9d2da556fb2837760637462b05dac5/index.js#L45) since it would try to get the parent directory of the value of `options.directory` instead of using `options.directory` directly. In terms of semver, this seems fuzzy to me; we're fixing a config defaulting bug by requiring a new option if you don't supply a config. A patch doesn't seem totally right here. 

The `directory` option would then need to be [passed through filing-cabinet](https://github.com/mrjoelkemp/node-filing-cabinet/blob/737cbb26320eb1b4347cdd0de7332fa07b7abdb0/index.js#L104-L110). That would be a patch that will get [passed through to dependency-tree](https://github.com/mrjoelkemp/node-dependency-tree/blob/master/package.json#L35). 

It turns out that dependency-tree is [already passing down](https://github.com/mrjoelkemp/node-dependency-tree/blob/master/index.js#L143) the directory to filing-cabinet (from the previous version of module-lookup-amd) that I described above, so no adjustments need to be made to that lib. Although, tests for this issue would be great to prevent regressions at the dependency-tree layer. 

The modular nature of this system makes for a lot of touch points, but each change isn't too complex. Are you up for submitting PRs for the various layers? Otherwise, I can start working on this tonight.

Thanks again for the report!

**Comment by pahen** [comment]
Sounds like a good plan! I don't have the time for PRs tonight. Still working out some stuff in madge for the v1.0 release. But I'm planning to do some other PRs later for you :)

Regarding https://github.com/mrjoelkemp/node-module-lookup-amd/blob/9baec9eb3f9d2da556fb2837760637462b05dac5/index.js#L45. We could add a check and only run `path.dirname()` on `configPath` if it's a file?

**Comment by pahen** [comment]
I can take a look at this tomorrow :)

**Comment by pahen** [comment]
I did the changes locally and it looks promising. PR's coming up!

**Comment by mrjoelkemp** [comment]
You're the man! Thanks for your effort here

**Comment by pahen** [comment]
All good now! :)
